### PR TITLE
Rename reserved Configuration to ButtonConfiguration

### PR DESCRIPTION
**Pull request by WyattMufson**
In Swift 5.5 there's now a built in class [UIButton.Configuration](https://developer.apple.com/documentation/uikit/uibutton/configuration). I've renamed the Delighted class from `Configuration` to `ButtonConfiguration`.

### CODE REVIEW

**Comment by erikpilz** [comment]
@WyattMufson, the `Configuration` struct is home to a few things that aren't specific to buttons. For example, the `pusher` attribute contains information about the WebSocket session and the `theme` attribute has settings that describe the card. What do you think about renaming this to something like `SurveyConfiguration`, `SessionConfiguration`, or something else more general?

**Comment by WyattMufson** [comment]
I agree, I'll change it to `SurveyConfiguration`

**Comment by WyattMufson** [comment]
@erikpilz fixed it

**Comment by erikpilz** [comment]
@WyattMufson Merged. Thanks for the help!

**Comment by WyattMufson** [comment]
Great!

**Pull request merged**
